version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: on_demand_marketplace
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  postgres_data:
