"""add category column to services table

Revision ID: 79311eb7d5d7
Revises: a1eab1f7fea5
Create Date: 2024-08-11 20:01:20.829606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79311eb7d5d7'
down_revision: Union[str, None] = 'a1eab1f7fea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_column('services', 'category')
    # ### end Alembic commands ###
