"""add service_tags table and location column to services table

Revision ID: a1eab1f7fea5
Revises: a2c75d5015a3
Create Date: 2024-08-10 14:44:52.349876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1eab1f7fea5"
down_revision: Union[str, None] = "a2c75d5015a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_tags_id"), "services_tags", ["id"], unique=False)
    op.add_column("services", sa.Column("location", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_services_location"), "services", ["location"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_location"), table_name="services")
    op.drop_column("services", "location")
    op.drop_index(op.f("ix_services_tags_id"), table_name="services_tags")
    op.drop_table("services_tags")
    # ### end Alembic commands ###
