"""updated service table

Revision ID: b7d26253ddc2
Revises: 79311eb7d5d7
Create Date: 2024-08-13 23:32:08.384862

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7d26253ddc2'
down_revision: Union[str, None] = '79311eb7d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services',
                  sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_services_search_vector', 'services', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_search_vector', table_name='services', postgresql_using='gin')
    op.drop_column('services', 'search_vector')
    # ### end Alembic commands ###
